In [1]:
import torch
import numpy as np

In [3]:
torch.cuda.is_available()

False

In [4]:
!nvidia-smi

Tue May  2 20:00:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.36       Driver Version: 512.36       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P3    15W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
some_data = [[1,2],[3,4]]
some_data

[[1, 2], [3, 4]]

In [6]:
type(some_data)

list

In [7]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [11]:
some_data = torch.tensor(some_data)
some_data

C:\Users\nikhi\AppData\Local\Temp\ipykernel_44412\3611831938.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  some_data = torch.tensor(some_data)


tensor([[1, 2],
        [3, 4]])

In [12]:
type(some_data)

torch.Tensor

In [13]:
some_data.dtype

torch.int64

In [14]:
nummpy_array = np.random.rand(3,4)
nummpy_array

array([[0.53424518, 0.09170572, 0.43794931, 0.68361728],
       [0.07319078, 0.86237566, 0.35494504, 0.06979237],
       [0.1446321 , 0.50854928, 0.40863268, 0.63776262]])

In [16]:
torch.from_numpy(nummpy_array)

RuntimeError: Numpy is not available

In [17]:
torch.tensor(nummpy_array)

tensor([[0.5342, 0.0917, 0.4379, 0.6836],
        [0.0732, 0.8624, 0.3549, 0.0698],
        [0.1446, 0.5085, 0.4086, 0.6378]])

In [19]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
torch.rand(3,4)

tensor([[0.9780, 0.1052, 0.8661, 0.2396],
        [0.1971, 0.3219, 0.3589, 0.7685],
        [0.8658, 0.9957, 0.7364, 0.6223]])

In [23]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.6763, 0.9107, 0.5686, 0.0304],
        [0.4058, 0.1785, 0.6977, 0.5959],
        [0.3577, 0.1525, 0.8209, 0.4903]])

In [24]:
my_tensor.dtype

torch.float32

In [25]:
my_tensor.device

device(type='cpu')

In [26]:
my_tensor.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [27]:
my_tensor


tensor([[0.6763, 0.9107, 0.5686, 0.0304],
        [0.4058, 0.1785, 0.6977, 0.5959],
        [0.3577, 0.1525, 0.8209, 0.4903]])

In [28]:
my_tensor[:,1:3]


tensor([[0.9107, 0.5686],
        [0.1785, 0.6977],
        [0.1525, 0.8209]])

In [29]:
my_tensor.mul(my_tensor)

tensor([[0.4573, 0.8295, 0.3233, 0.0009],
        [0.1646, 0.0319, 0.4868, 0.3551],
        [0.1279, 0.0233, 0.6738, 0.2404]])

In [30]:
my_tensor * my_tensor

tensor([[0.4573, 0.8295, 0.3233, 0.0009],
        [0.1646, 0.0319, 0.4868, 0.3551],
        [0.1279, 0.0233, 0.6738, 0.2404]])

In [31]:
my_tensor.matmul(my_tensor.T)

tensor([[1.6110, 0.8518, 0.8625],
        [0.8518, 1.0385, 1.0373],
        [0.8625, 1.0373, 1.0655]])

In [32]:
torch.matmul(my_tensor,my_tensor.T)

tensor([[1.6110, 0.8518, 0.8625],
        [0.8518, 1.0385, 1.0373],
        [0.8625, 1.0373, 1.0655]])

In [33]:
my_tensor @ my_tensor.T

tensor([[1.6110, 0.8518, 0.8625],
        [0.8518, 1.0385, 1.0373],
        [0.8625, 1.0373, 1.0655]])

In [34]:
my_tensor.sum(axis=1)

tensor([2.1860, 1.8779, 1.8215])

In [35]:
my_tensor.sum(axis=0)

tensor([1.4397, 1.2418, 2.0872, 1.1167])

In [36]:
## Torch.min & torch.max


In [37]:
torch.cat(tensors=[my_tensor,my_tensor],dim=1)

tensor([[0.6763, 0.9107, 0.5686, 0.0304, 0.6763, 0.9107, 0.5686, 0.0304],
        [0.4058, 0.1785, 0.6977, 0.5959, 0.4058, 0.1785, 0.6977, 0.5959],
        [0.3577, 0.1525, 0.8209, 0.4903, 0.3577, 0.1525, 0.8209, 0.4903]])

In [38]:
torch.concat(tensors=[my_tensor,my_tensor],dim=1)

tensor([[0.6763, 0.9107, 0.5686, 0.0304, 0.6763, 0.9107, 0.5686, 0.0304],
        [0.4058, 0.1785, 0.6977, 0.5959, 0.4058, 0.1785, 0.6977, 0.5959],
        [0.3577, 0.1525, 0.8209, 0.4903, 0.3577, 0.1525, 0.8209, 0.4903]])

In [39]:
torch.nn.functional.softmax(my_tensor,dim=1)

tensor([[0.2713, 0.3430, 0.2436, 0.1422],
        [0.2301, 0.1834, 0.3082, 0.2783],
        [0.2200, 0.1792, 0.3496, 0.2512]])

In [40]:
torch.nn.functional.softmax(my_tensor,dim=0)

tensor([[0.4016, 0.5130, 0.2920, 0.2302],
        [0.3064, 0.2467, 0.3322, 0.4052],
        [0.2920, 0.2403, 0.3758, 0.3646]])

In [41]:
my_tensor.shape

torch.Size([3, 4])

In [42]:
my_tensor.size()

torch.Size([3, 4])

In [43]:
torch.rand(10,3,128,128).size()

torch.Size([10, 3, 128, 128])

In [44]:
my_tensor

tensor([[0.6763, 0.9107, 0.5686, 0.0304],
        [0.4058, 0.1785, 0.6977, 0.5959],
        [0.3577, 0.1525, 0.8209, 0.4903]])

In [46]:
my_tensor.clip(0.2,0.8)

tensor([[0.6763, 0.8000, 0.5686, 0.2000],
        [0.4058, 0.2000, 0.6977, 0.5959],
        [0.3577, 0.2000, 0.8000, 0.4903]])

In [47]:
my_tensor.cup().detach().numpy()

AttributeError: 'Tensor' object has no attribute 'cup'