# Pytorch Autograd

In [1]:
# Autograd is used in the back propagation of neural network to calculate the gradients of error w.r.t different parameters.

In [2]:
import torch

In [3]:
a = torch.tensor([5.],requires_grad=True)
b = torch.tensor([6.],requires_grad=True)

C:\Users\nikhi\AppData\Local\Temp\ipykernel_39956\3055711437.py:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  a = torch.tensor([5.],requires_grad=True)


In [4]:
a

tensor([5.], requires_grad=True)

In [5]:
b

tensor([6.], requires_grad=True)

In [6]:
y = a**3-b**2

In [7]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [8]:
#dy/da = 3*a**2 =75
#dy/db = -2b = -12

In [9]:
a.grad

In [10]:
b.grad

In [11]:
y.backward()

In [12]:
a.grad

tensor([75.])

In [13]:
b.grad

tensor([-12.])

In [14]:
# Weight
W = torch.randn(10,1,requires_grad=True)
# Bais
b = torch.randn(1,requires_grad=True)

In [15]:
W

tensor([[ 0.3874],
        [-1.2039],
        [-0.5078],
        [-0.7383],
        [ 1.1308],
        [ 0.7675],
        [-0.0032],
        [ 1.2959],
        [-0.2326],
        [-0.6044]], requires_grad=True)

In [16]:
b

tensor([-2.3498], requires_grad=True)

In [17]:
x = torch.rand(1,10)

In [18]:
x

tensor([[0.6245, 0.1284, 0.8207, 0.9281, 0.8835, 0.2299, 0.7909, 0.3432, 0.0902,
         0.3125]])

In [19]:
output = torch.matmul(x,W)+b
output

tensor([[-1.9566]], grad_fn=<AddBackward0>)

In [20]:
loss = 1- output
loss

tensor([[2.9566]], grad_fn=<RsubBackward1>)

In [21]:
loss.backward()

In [22]:
W.grad

tensor([[-0.6245],
        [-0.1284],
        [-0.8207],
        [-0.9281],
        [-0.8835],
        [-0.2299],
        [-0.7909],
        [-0.3432],
        [-0.0902],
        [-0.3125]])

In [23]:
b.grad

tensor([-1.])

In [24]:
with torch.no_grad():
    learning_rate = 0.001
    W = W - learning_rate * W.grad.data

In [25]:
W

tensor([[ 0.3880],
        [-1.2038],
        [-0.5070],
        [-0.7373],
        [ 1.1317],
        [ 0.7677],
        [-0.0024],
        [ 1.2962],
        [-0.2325],
        [-0.6041]])

In [26]:
b

tensor([-2.3498], requires_grad=True)